cmake_minimum_required(VERSION 3.21)
project(vpack_interop LANGUAGES CXX C)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(UseIPO OFF CACHE STRING "" FORCE)
set(BuildSseOpt OFF CACHE BOOL "" FORCE)
add_subdirectory("${VPACK_SOURCE}" upstream EXCLUDE_FROM_ALL)
add_library(vpack_reference SHARED reference.cpp)
target_link_libraries(vpack_reference PRIVATE velocypack)
target_compile_definitions(vpack_reference PRIVATE VPACK_REFERENCE_REVISION="${VPACK_REVISION}")
target_compile_options(vpack_reference PRIVATE -Wall -Wextra -Wpedantic)
