name: Java CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 8
          - 11
          - 15

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Info
        run: mvn -version
      - name: Test
        run: mvn -e --no-transfer-progress test
