name: Java CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  test:

    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 8
          - 11
          - 17
          - 19

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java-version}}
          distribution: 'adopt'
          cache: maven
      - name: Info
        run: mvn -version
      - name: Test
        run: mvn -e --no-transfer-progress test

  jackson-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        jackson-version:
          - 2.14.1
          - 2.13.4
          - 2.12.7
          - 2.11.4
          - 2.10.5
        java-version:
          - 17

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java-version}}
          distribution: 'adopt'
          cache: maven
      - name: Info
        run: mvn -version
      - name: Test
        run: mvn --no-transfer-progress test -Djackson.version=${{matrix.jackson-version}}
